### ISSUE TITLE
Using clebA dataset

### ISSUE THREAD

**Issue by nile649** [Latope2-150/Progressive_Growing_of_GANs-PyTorch#2]
I tried using celebA dataset, but it is not working, any suggestion you could make?

**Comment by jeromerony** [comment]
Well, I would need a few more details / a code sample to reproduce the problem

**Comment by nile649** [comment]
1.) I am passing the images using pytorch's dataloader module. 2.) I have changed the output of generator to 3 channel, and discriminator to accept 3 channel Image.

Other than this I have not made any changes to your code.

**Comment by nile649** [comment]
My mistake it works very well

**Comment by superhans** [comment]
@nile649 Could you share the modifications you made to run it on a custom dataset ?

**Comment by nile649** [comment]
could you post your code? so i can point out changes.
Thanks

**Comment by superhans** [comment]
So far I have done the same as you (changed the dataloader module and changed it to 3 channel).

But I'm trying to figure out how to this exact thing on larger images (say, 224x224). Shouldn't the discriminator accept larger and larger resolutions with time ? 

Right now, unless transforms.Resize((32, 32)), is 32x32, it will crash with the error "RuntimeError: The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 3"

My question essentially is : what changes do I need to make to get this to work on input images larger than 32x32?

**Comment by jeromerony** [comment]
Hi,

So basically, the size of the image should be the same both at the output of the generator and at the input of the discriminator.

If you want to make it work on images of, let's say 256x256, you need to set the `MAX_RES = 6` because the output will be of size `4 * 2 ^ MAX_RES`. This MAX_RES parameter will condition the output and input sizes of G and D. To train the networks with these sizes, you need to have a dataset with images of this size, so your Dataset (with the transform) should always return images of size 256x256. They are [resized in the train loop](https://github.com/jeromerony/Progressive_Growing_of_GANs-PyTorch/blob/ca64cdff8fb5db951153ea86f349809ee566d296/mnist_example.py#L133) to match the current train size of the networks.

If you want to use for images that have a size that is different from a power of 2, you need to tweak the kernel_size and padding of the [first layer in the generator](https://github.com/jeromerony/Progressive_Growing_of_GANs-PyTorch/blob/ca64cdff8fb5db951153ea86f349809ee566d296/model.py#L25) and the kernel size of the  'conv_pool' [layer in the discriminator](https://github.com/jeromerony/Progressive_Growing_of_GANs-PyTorch/blob/ca64cdff8fb5db951153ea86f349809ee566d296/model.py#L99).
I can help you on that if you need.

**Comment by superhans** [comment]
I was mostly able to get this to work correctly.
